{
 "title": "PI-Hole Exporter",
 "description": "This is a PI-Hole dashboard when using the https://github.com/eko/pihole-exporter Prometheus exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(pihole_ads_blocked_today, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "🍓PI-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_status{hostname=~'$node'}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pihole_unique_domains{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Cache hit/miss ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pihole_queries_cached{hostname=~'$node'}[$__range])) / (sum(increase(pihole_queries_cached{hostname=~'$node'}[$__range])) + sum(increase(pihole_queries_forwarded{hostname=~'$node'}[$__range])))",
     "legendFormat": "hit"
    }
   ]
  },
  {
   "title": "Cache hit/miss ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(pihole_queries_cached{hostname=~'$node'}[$__range]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(increase(pihole_queries_forwarded{hostname=~'$node'}[$__range]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(pihole_dns_queries_all_types{hostname=~'$node'}[5m]) < 300",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pihole_forward_destinations{hostname=~'$node'}",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  {
   "title": "Hit/Miss Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(pihole_queries_cached{hostname=~'$node'}[5m]) < 200",
     "legendFormat": "hit"
    },
    {
     "expr": "irate(pihole_queries_forwarded{hostname=~'$node'}[5m]) < 200",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Ads blocking rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(pihole_ads_blocked_today{hostname=~'$node'}[5m]) < 50",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Unique clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_unique_clients{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS queries all of types",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pihole_dns_queries_all_types{hostname=~'$node'}",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Ads blocked (today)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pihole_ads_blocked_today{hostname=~'$node'}",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "% of ads blocked",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "pihole_ads_percentage_today", "legendFormat": "{{ job }}" }
     ]
    }
   ]
  }
 ]
}